<?php

namespace App\Http\Requests\Quote;

use Illuminate\Foundation\Http\FormRequest;

class StoreQuoteRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\Rule|array|string>
     */
    public function rules(): array
    {
        return [
            'title' => 'required',
            'title_ka' => 'required',
            'img' => 'required',
            'movie_id' => 'required|exists:movies,id',
        ];
    }
    public function validated($key = null, $default = null)
    {
        $validated = parent::validated($key, $default); // TODO: Change the autogenerated stub
        $titles = [
            'en' => $validated['title'],
            'ka' => $validated['title_ka']
        ];
        $validated['title'] = $titles;
        $validated['movie_id'] = $validated['movie_id'];
        return $validated;
    }
}
